apiVersion: v1
kind: pod
metadata: 
  name: pod-config
spec: 
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom: 
        configMapKeyRef:
          name: csvdaws78s
          key: course
    - name: trainer
      valueFrom:
        configMapKerRef:
          name: csvdaws78s
          key: trainer 